name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '>=18.x'
      - uses: actions/checkout@master
      - name: Build
        uses: patrickweaver/actions-eleventy@upgrade-node-22
        with:
          args: --output dist
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}